# Generated by Django 4.1.7 on 2023-02-23 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='branch',
            new_name='bank',
        ),
    ]
