# Generated by Django 4.1.7 on 2023-02-26 19:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('banks', '0002_rename_branch_branch_bank'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='address',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AddField(
            model_name='branch',
            name='capacity',
            field=models.PositiveIntegerField(default=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='email',
            field=models.EmailField(default='admin@utoronto.ca', max_length=254),
        ),
        migrations.AddField(
            model_name='branch',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='name',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AddField(
            model_name='branch',
            name='transit_number',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=True, max_length=100)),
                ('swift_code', models.CharField(default=True, max_length=100)),
                ('inst_num', models.CharField(default=True, max_length=100)),
                ('description', models.CharField(default=True, max_length=100)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='branch',
            name='bank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branches', to='banks.bank'),
        ),
        migrations.DeleteModel(
            name='Banks',
        ),
    ]
