# Generated by Django 4.1.7 on 2023-02-26 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0003_branch_address_branch_capacity_branch_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='transit_number',
            new_name='transit_num',
        ),
    ]
