# Generated by Django 4.1.7 on 2023-02-27 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0004_rename_transit_number_branch_transit_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='description',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bank',
            name='inst_num',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bank',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bank',
            name='swift_code',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='branch',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='branch',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='branch',
            name='transit_num',
            field=models.CharField(max_length=100),
        ),
    ]
